### ISSUE TITLE
`v1.0-SNAPSHOT` fails to start.

### ISSUE THREAD

**Issue by Pheotis** [Bilicraft-Community/StargateDynmap#2]
```java
[19:11:21] [Server thread/INFO]: [Stargate] Enabling Stargate v1.0.0.4-ALPHA
[19:11:21] [Server thread/INFO]: [dynmap] Enabling dynmap v3.4-beta-3-774
[19:11:22] [Server thread/INFO]: [dynmap] Added 18 custom biome mappings
[19:11:22] [Server thread/INFO]: [dynmap] Using LuckPerms 5.4.25 for access control
[19:11:22] [Server thread/INFO]: [dynmap] Extracted files upgraded
[19:11:22] [Server thread/INFO]: [dynmap] Mod Support processing completed
[19:11:27] [Server thread/INFO]: [dynmap] Loaded 27 shaders.
[19:11:27] [Server thread/INFO]: [dynmap] Loaded 83 perspectives.
[19:11:27] [Server thread/INFO]: [dynmap] Loaded 22 lightings.
[19:11:27] [Server thread/INFO]: [dynmap] Starting enter/exit processing
[19:11:27] [Dynmap Render Thread/INFO]: [dynmap] Finish marker initialization
[19:11:28] [Server thread/INFO]: [dynmap] Web server started on address 0.0.0.0:8123
[19:11:28] [Server thread/INFO]: [dynmap] version 3.4-beta-3-774 is enabled - core version 3.4-beta-3-774
[19:11:28] [Server thread/INFO]: [dynmap] For support, visit our Discord at https://discord.gg/s3rd5qn
[19:11:28] [Server thread/INFO]: [dynmap] For news, visit https://reddit.com/r/Dynmap or follow https://twitter.com/Dynmap
[19:11:28] [Server thread/INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[19:11:28] [Server thread/INFO]: [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
[19:11:28] [Server thread/INFO]: [dynmap] Loaded 3 maps of world 'world'.
[19:11:28] [Server thread/INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
[19:11:28] [Server thread/INFO]: [dynmap] Enabled
[19:11:28] [Server thread/INFO]: [SG-Dynmap] Enabling SG-Dynmap v1.0-SNAPSHOT
[19:11:28] [Server thread/ERROR]: Error occurred while enabling SG-Dynmap v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.api.StargateAPI.getRegistry()" because "this.stargateAPI" is null
        at com.bilicraft.stargatedynmap.StargateDynmap.getAllPortals(StargateDynmap.java:70) ~[?:?]
        at com.bilicraft.stargatedynmap.StargateDynmap.updatePortals(StargateDynmap.java:80) ~[?:?]
        at com.bilicraft.stargatedynmap.StargateDynmap.onEnable(StargateDynmap.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by EpicKnarvik97** [comment]
It seems `stargateAPI = (StargateAPI) Bukkit.getPluginManager().getPlugin("stargate");` either returns null, or stargateAPI is used before initialization.

The null could potentially be because of case sensitivity I guess? "Stargate" instead of "stargate".
It could be that it's trying to hook into Stargate before Stargate is properly enabled, but as it's listed as a dependency, that shouldn't happen.
