### ISSUE TITLE
Possible issue with setDescription(String).

### ISSUE THREAD

**Issue by Pheotis** [Bilicraft-Community/StargateDynmap#3]
Crosspost; see https://github.com/stargate-rewritten/Stargate-Bukkit/issues/194

**Comment by Pheotis** [comment]
Coppied from the SGR issue:

In certain unknown circumstances, when:
 - As an online player
 - Trying to make a fixed gate
 - at 22.5 -59 22.5
 - on a new, non-existant, network
 - To a non-existant destination
 - as a user with default permissions, except for a node that doesn't exist

In the `vault_3` environment, running the most recent spigot, with a fresh install of SG, SGD, and SGC.

```java
>lp user pheotis permission set sg.preset.gatebuilder
[12:58:00] [luckperms-command-executor/INFO]: [LP] Set sg.preset.gatebuilder to true for pheotis in context global.
[12:58:09] [Server thread/INFO]: [Stargate] Checking permissions for entity CraftPlayer{name=Pheotis}
[12:58:10] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'NET_DENY' to 'You do not have access to that network!'
[12:58:10] [Server thread/INFO]: [Stargate]  Player does not have perms to create on current network 222189. Checking for private with same network name...
[12:58:10] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'NET_DENY' to 'You do not have access to that network!'
[12:58:10] [Server thread/INFO]: [Stargate]  Player does not have perms to create on current network {222189}. Replacing to private network with the players name...
[12:58:10] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'GATE_CREATE_FALLBACK' to 'Unable to create your gate on the %network% network; trying your personal network instead!'
[12:58:10] [Server thread/INFO]: [Stargate] Amount of GateFormats: 1
[12:58:10] [Server thread/INFO]: [Stargate] --------- nether.gate ---------
[12:58:10] [Server thread/INFO]: [Stargate] Checking create permissions
[12:58:10] [Server thread/INFO]: [Stargate]  Checking permission 'sg.create.world.world'. returned true
[12:58:10] [Server thread/INFO]: [Stargate]  Checking permission 'sg.create.network.personal'. returned true
[12:58:10] [Server thread/INFO]: [Stargate]  Checking permission 'sg.create.design.nether'. returned true
[12:58:10] [Server thread/INFO]: [Stargate]  Network is not full, maxGates = %s
[12:58:10] [Server thread/ERROR]: Could not pass event StargateCreateEvent to SG-Dynmap v1.1-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.TheDgtl.Stargate.util.portal.PortalCreationHelper.tryPortalCreation(PortalCreationHelper.java:115) ~[?:?]
        at net.TheDgtl.Stargate.listener.BlockEventListener.onSignChange(BlockEventListener.java:154) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2692) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.network.PlayerConnection.lambda$19(PlayerConnection.java:2649) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.network.PlayerConnection.lambda$2(PlayerConnection.java:438) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.dynmap.markers.Marker.setDescription(String)" because "marker" is null
        at com.bilicraft.stargatedynmap.StargateDynmap.addPortalMarker(StargateDynmap.java:150) ~[?:?]
        at com.bilicraft.stargatedynmap.StargateDynmap.portalEvent(StargateDynmap.java:73) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 30 more
[12:58:10] [Server thread/INFO]: [Stargate]  player has permission = true
[12:58:10] [Server thread/INFO]: [Stargate] Charging player 1
[12:58:10] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'ECO_DEDUCT' to 'Deducted %cost%.'
[12:58:10] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'ALREADY_EXIST' to 'A gate by that name already exists!'
>lp user pheotis permission info
[13:01:34] [luckperms-command-executor/INFO]: [LP] pheotis's Permissions:  (page 1 of 1 - 1 entries)
[13:01:34] [luckperms-command-executor/INFO]: > sg.preset.gatebuilder
```

**Comment by Pheotis** [comment]
> It would appear that this reproduces consistently by, once running vault_2, placing the following portal sign at 25 -58 21.
(Might only reproduce as my user)
> 
> This appears to reproduce with any sign at those coordinates if the third line is the network attempted (222189)
> 
> ![image](https://user-images.githubusercontent.com/49039536/172442941-f353bb55-a26c-4219-85a8-3171fe50dc9d.png)
> 
> This is the most recent beta, which supports 1.18.2.
> As this is a dynmap issue, going to close this and move it over to https://github.com/stargate-rewritten/SG-Dynmap/issues/3

**Comment by EpicKnarvik97** [comment]
The quick fix is to just check for null markers, but we should probably try and fix the problem properly. It could be a problem because of the negative y, or it could be something else. We should probably try to eliminate negative y first.

**Comment by Pheotis** [comment]
Not sure how the negative y could be causing this problem:
8 other portals at the same height have already been successfully tested on the problematic instance.

![image](https://user-images.githubusercontent.com/49039536/172444448-e3605bdc-2a2d-4cbe-b66e-d83faa479751.png)

**Comment by Thorinwasher** [comment]
Can only be null if the marker id is already in use, if the image icon is invalid, or if the icon is not allowed:
```java
        if(markers.containsKey(id)) return null;    /* Duplicate ID? */
        if(!(icon instanceof MarkerIconImpl)) return null;
        /* If limited icons, and this isn't valid one, quit */
        if((allowedicons != null) && (allowedicons.containsKey(icon.getMarkerIconID()) == false)) return null;
```

**Comment by Thorinwasher** [comment]
As (probably) knarvik added a null pointer safeguard, I would say this current implementation is fine
